'use strict';
const FOOD_ICON='<svg class="food-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M5 3v6a3 3 0 0 0 6 0V3M8 3v18M18 3c-2 2-3 5-3 9h4V3h-1ZM19 12v9"/></svg>';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const C=globalThis.TRAVEL_CONFIG||{}, FRIEND=C.friend||'희수', MAP_LABEL=C.mapLabel||'구글지도', REGIONS=C.regions||['홍콩섬','구룡','근교','마카오'];
const KEY=C.storageKey||'hkmo_planner_v2';
const located=p=>p&&Number.isFinite(p.lat)&&Number.isFinite(p.lng);
const available=p=>located(p)&&!p.unavailable;
const region=p=>p.region||C.defaultRegion||(p.lat<22.22&&p.lng<113.6?'마카오':p.color==='#27ae60'?'근교':p.lat>=22.292?'구룡':'홍콩섬');
const catalog=[...BASE_SPOTS.map(p=>({...p,id:String(p.id),region:region(p)})),...(C.restaurants||HEESU_RESTAURANTS),...(globalThis.YOONHWAN_RESTAURANTS||[])];
const FRIEND_RESTAURANTS=C.restaurants||HEESU_RESTAURANTS;
let db={version:2,active:'',trips:[]},current=0,section='schedule',filter='전체',query='',undo=[],map,markerLayer,routeLayer,transitLayer,locationLayer,markers=new Map(),transit=false,toastTimer;
function foodSection(){return section==='heesu'||section==='yoonhwan';}
function friendName(){return section==='yoonhwan'?'윤환':FRIEND;}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500);}
function trip(){return db.trips.find(t=>t.id===db.active)||db.trips[0];}
function places(){return [...catalog,...trip().custom];}
function getPlace(id){return places().find(p=>p.id===id);}
function save(){try{localStorage.setItem(KEY,JSON.stringify(db));$('#save-status').textContent='✓ 이 기기에 저장됨';}catch(e){$('#save-status').textContent='저장 실패 · 백업 필요';toast('기기에 저장하지 못했어요. ⋯ 메뉴에서 백업을 내려받아 주세요.');}}
function mutate(fn){undo.push(JSON.stringify(trip()));if(undo.length>30)undo.shift();fn();save();render();}
function initState(){
  try{const raw=JSON.parse(localStorage.getItem(KEY));if(raw?.version===2&&Array.isArray(raw.trips)){
    db.trips=raw.trips.flatMap(t=>{try{return [Planner.normalize(t,catalog)];}catch{return [];}});db.active=raw.active;
  }}catch{toast('저장 데이터를 읽지 못했어요. 백업 파일이 있으면 복원해 주세요.');}
  if(!db.trips.length){let t;try{const old=C.city?null:JSON.parse(localStorage.getItem('hkmo_planner_v1'));if(old?.assignment)t=Planner.legacy(old,catalog);}catch{}
    if(!t){t=Planner.fresh();if(C.initialStops){C.initialStops.forEach((ids,i)=>t.days[i].stops=ids.map(id=>({id})));}else{t.days[0].stops=['9','2','1','10'].map(id=>({id}));t.days[2].stops=['28','27','35'].map(id=>({id}));}t=Planner.normalize(t,catalog);}db.trips=[t];db.active=t.id;
  }
  if(!db.trips.some(t=>t.id===db.active))db.active=db.trips[0].id;
  importHash();save();
}
function importHash(){if(!location.hash)return;try{
  const t=Planner.fromHash(location.hash,catalog);if(!t)return;
  const key=location.hash;
  let existing;try{existing=sessionStorage.getItem(KEY+'_shared_'+key);}catch{}
  if(existing&&db.trips.some(x=>x.id===existing)){db.active=existing;return;}
  t.id=Planner.id();t.name+=' · 공유받음';db.trips.push(t);db.active=t.id;
  try{sessionStorage.setItem(KEY+'_shared_'+key,t.id);}catch{}
  try{history.replaceState(null,'',location.pathname+location.search);}catch{}
  toast('공유 일정을 별도 여행으로 열었어요.');
}catch{toast('공유 링크를 읽지 못했어요. 기존 일정은 유지됩니다.');}}
const google=p=>p.googleUrl|| (C.placeLink?C.placeLink(p):'https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(p.address?`${p.englishName||p.name} ${p.address}`:`${p.lat},${p.lng}`));
function directions(a,b,mode='transit'){if(C.directions)return C.directions(a,b,mode);const params=new URLSearchParams({api:'1',destination:b.address?`${b.englishName||b.name} ${b.address}`:`${b.lat},${b.lng}`,travelmode:mode});if(a)params.set('origin',`${a.lat},${a.lng}`);return 'https://www.google.com/maps/dir/?'+params;}
const external=(url,label)=>`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
function initMap(){if(!window.L){$('#map-fallback').hidden=false;return;}map=L.map('map',{zoomControl:true,zoomAnimation:false,fadeAnimation:false,markerZoomAnimation:false}).setView(C.center||[22.29,114.165],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(map);markerLayer=L.layerGroup().addTo(map);routeLayer=L.layerGroup().addTo(map);transitLayer=L.layerGroup();locationLayer=L.layerGroup().addTo(map);
  Object.values(mtrLines).forEach(line=>{L.polyline(line.stations.map(s=>[s.lat,s.lng]),{color:line.color,weight:4,opacity:.45}).addTo(transitLayer);line.stations.forEach(s=>L.circleMarker([s.lat,s.lng],{radius:3,color:line.color,fillColor:'#fff',fillOpacity:1,weight:2}).bindTooltip(esc(s.name)).addTo(transitLayer));});
  [ferryRoute,macauFerryRoute].filter(p=>p.length).forEach(p=>L.polyline(p,{color:'#569caa',weight:3,dashArray:'7 7'}).bindTooltip('페리 항로 참고').addTo(transitLayer));
  new ResizeObserver(()=>map.invalidateSize()).observe($('#map-panel'));
  map.on('zoomend moveend resize',layoutFoodLabels);
}
function visiblePlaces(){const all=places();if(section==='schedule')return trip().days[current].stops.map(s=>getPlace(s.id)).filter(Boolean);
  return all.filter(p=>(!foodSection()||(section==='yoonhwan'?p.recommender==='윤환':p.heesu&&p.recommender!=='윤환'))&&(filter==='전체'||region(p)===filter||p.tags?.includes(filter)||(filter==='필수'&&p.must)||(filter==='먹거리'&&(p.heesu||p.tags?.includes('먹거리')))||(filter==='아이 동반'&&p.tags?.some(t=>/아이★{4}/.test(t)))||(filter==='추천만'&&!p.unavailable&&p.verdict!=='취향 아님'&&p.verdict!=='참고'))&&[p.name,p.desc,p.address,...(p.tags||[]),...(p.menus||[])].join(' ').toLowerCase().includes(query.toLowerCase()));
}
function popup(p){const div=document.createElement('div');div.className='popup-body';div.innerHTML=`<strong class="popup-title">${esc(p.name)}</strong>${p.heesu?'<span class="tag">'+esc(p.recommender||FRIEND)+'의 '+esc(p.verdict||'추천')+'</span>':''}${p.status?`<p class="place-status">${esc(p.status)}</p>`:''}${p.menus?.length?`<p><b>주요 메뉴</b><br>${esc(p.menus.join(' · '))}</p>`:''}<p><b>주소</b><br>${esc(p.address||'상세 주소 미등록 · 지도 위치로 길찾기')}</p>${p.branchNote?`<p class="help">${esc(p.branchNote)}</p>`:''}${p.desc?`<p>${esc(p.desc)}</p>`:''}<p>${external(google(p),MAP_LABEL+'에서 보기')}</p>${p.coordinateNote?`<p class="help">${esc(p.coordinateNote)}</p>`:''}${p.source?`<p class="help">${external(p.source,'주소 출처')}</p>`:''}`;
  const neighbors=catalog.filter(x=>x.id!==p.id&&located(x)&&x.lat===p.lat&&x.lng===p.lng);if(neighbors.length){const group=document.createElement('p');group.className='help';group.textContent='같은 건물의 추천: ';neighbors.forEach(x=>{const b=document.createElement('button');b.textContent=x.name;b.onclick=()=>focusPlace(x.id);group.append(b);});div.append(group);}
  if(p.img){const photo=document.createElement('button');photo.textContent='사진 크게 보기';photo.onclick=()=>openDialog(p.name,`<img style="width:100%;border-radius:10px" src="${esc(p.img.replace('width=400','width=1000'))}" alt="${esc(p.name)}">`);div.append(photo);}
  const btn=document.createElement('button');btn.disabled=!available(p);btn.textContent=available(p)?'Day '+(current+1)+'에 담기':p.unavailable?'영업 확인 후 방문':'지점 위치 확인 필요';btn.onclick=()=>add(p.id);div.append(btn);return div;}
function drawMap(fit=false){if(!map)return;markerLayer.clearLayers();routeLayer.clearLayers();markers.clear();const list=visiblePlaces(),d=trip().days[current],bounds=[];
  list.forEach((p,i)=>{if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))return;const point=[p.lat,p.lng];bounds.push(point);const icon=L.divIcon({className:'',html:`<div class="pin ${p.heesu?'food':''}">${section==='schedule'?i+1:p.heesu?i+1:'•'}</div>`,iconSize:[30,30],iconAnchor:[15,15]});const marker=L.marker(point,{icon}).addTo(markerLayer).bindPopup(popup(p));markers.set(p.id,marker);
    if(foodSection())marker.bindTooltip(`<b>${i+1}. ${esc(p.name)}</b><small>${esc((p.menus||[]).join(' · '))}</small>`,{permanent:true,direction:'top',offset:[0,-16],opacity:1,className:'food-label',interactive:true});
  });
  if(section==='schedule'){
    if(d.hotel){const h=d.hotel;bounds.unshift([h.lat,h.lng]);L.marker([h.lat,h.lng],{icon:L.divIcon({className:'',html:'<div class="pin hotel">⌂</div>',iconSize:[30,30],iconAnchor:[15,15]})}).bindPopup(esc(h.name)).addTo(markerLayer);}
    if(bounds.length>1)L.polyline(d.hotel?[...bounds,bounds[0]]:bounds,{color:'#386c59',weight:3,opacity:.8,dashArray:'6 9'}).addTo(routeLayer);
  }
  if(fit&&bounds.length&&$('#map-panel').offsetWidth>0)map.fitBounds(L.latLngBounds(bounds),{padding:[65,100],maxZoom:15,animate:false});
  requestAnimationFrame(layoutFoodLabels);
}
function setView(view,fit=false){document.body.dataset.view=view;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.view===view));if(map)requestAnimationFrame(()=>{map.invalidateSize();if(fit)drawMap(true);});}
function focusPlace(id){const p=getPlace(id);if(!p)return;if(!located(p)){openDialog(p.name,popup(p));return;}document.querySelectorAll('.spot-card').forEach(c=>c.classList.toggle('selected',c.dataset.id===id));document.querySelectorAll('.pin.selected').forEach(p=>p.classList.remove('selected'));$('#map-title').textContent=p.name;$('#map-subtitle').textContent=region(p)+' · 선택한 장소';if(!located(p)||!map){openDialog(p.name,popup(p));return;}setView('map');if(!markers.has(id)){const m=L.marker([p.lat,p.lng]).addTo(markerLayer).bindPopup(popup(p));markers.set(id,m);}const target=markers.get(id);requestAnimationFrame(()=>{if(markers.get(id)!==target||!map.hasLayer(target))return;map.invalidateSize();map.stop();map.setView([p.lat,p.lng],16,{animate:false});target.getElement()?.querySelector('.pin')?.classList.add('selected');target.openPopup();});}
function card(p,stop,index){const assigned=trip().days.findIndex(d=>d.stops.some(s=>s.id===p.id));return `<article class="spot-card ${stop?.visited?'visited':''}" data-id="${esc(p.id)}" tabindex="0" aria-label="${esc(p.name)} 지도에서 위치 보기" ${stop?'draggable="true"':''}>
${stop?`<div class="time-line"><span class="stop-number">${index+1}</span><b>${esc(stop.time||'시간 미정')}</b>${stop.duration?`<span>· ${stop.duration}분 머물기</span>`:''}<button class="visit-toggle" data-action="visited" aria-pressed="${stop.visited}">${stop.visited?'✓ 다녀왔어요':'○ 방문 체크'}</button></div>`:''}
<div class="card-top">${p.img?`<img class="spot-thumb" src="${esc(p.img)}" alt="" loading="lazy" referrerpolicy="no-referrer">`:`<div class="spot-thumb spot-placeholder">${p.heesu?FOOD_ICON:'旅'}</div>`}<div class="card-copy"><div class="spot-meta">${esc(region(p))}${p.heesu?`<b>${esc(p.recommender||FRIEND)} · ${esc(p.verdict||'추천')}</b>`:p.must?'<b>MUST VISIT</b>':''}</div><button class="spot-name" data-action="focus">${esc(p.name)}</button>${p.menus?.length?`<div class="menus">${esc(p.menus.join(' · '))}</div>`:`<p class="spot-desc">${esc(p.desc)}</p>`}</div></div>
${p.status?`<p class="place-status">${esc(p.status)}</p>`:''}${p.heesu?`<p class="spot-desc">${esc(p.desc)}</p>${p.branchNote?`<p class="spot-desc">ⓘ ${esc(p.branchNote)}</p>`:''}`:''}
${!stop?`<div class="tags">${(p.tags||[]).slice(0,3).map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div>`:''}${stop?.note?`<div class="card-note">${esc(stop.note)}</div>`:''}
<div class="card-actions">${external(google(p),MAP_LABEL)}${stop?`<button data-action="edit">시간·메모</button><button data-action="up" aria-label="위로 이동" ${index===0?'disabled':''}>↑</button><button data-action="down" aria-label="아래로 이동" ${index===trip().days[current].stops.length-1?'disabled':''}>↓</button><button data-action="move" aria-label="다른 날로 이동 또는 일정에서 빼기">⋯</button>`:`<button class="add" data-action="add" ${available(p)?'':'disabled'}>${!available(p)?(p.unavailable?'영업 확인 필요':'지점 확인 필요'):assigned<0?'＋ 일정에 담기':`Day ${assigned+1}에 담음 · 이동`}</button>`}</div></article>`;}
function transfer(a,b,stop){return `<div class="transfer"><span>↳ 다음 장소까지</span><select data-mode="${esc(stop.id)}" aria-label="${esc(b.name)}까지 이동수단">${[['transit','대중교통'],['walking','도보'],['driving','차량']].map(([v,t])=>`<option value="${v}" ${stop.mode===v?'selected':''}>${t}</option>`).join('')}</select>${external(directions(a,b,stop.mode),'길찾기')}</div>`;}
function render(fit=false){const t=trip();current=Math.min(current,t.days.length-1);const d=t.days[current],list=visiblePlaces();$('#trip-select').innerHTML=db.trips.map(x=>`<option value="${esc(x.id)}" ${x.id===t.id?'selected':''}>${esc(x.name)}</option>`).join('');$('#trip-title').textContent=t.name;$('#trip-summary').textContent=`${t.start?Planner.date(t.start,0)+' 출발 · ':''}${t.days.length}일 여행 · ${t.days.reduce((n,d)=>n+d.stops.length,0)}곳을 담았어요`;
$('#day-tabs').innerHTML=t.days.map((d,i)=>`<button class="day-tab" data-day="${i}" aria-pressed="${current===i}">Day ${i+1}<small>${esc(Planner.date(t.start,i)||d.title)}</small></button>`).join('');$('#schedule-count').textContent=d.stops.length;
document.querySelectorAll('[data-section]').forEach(b=>b.setAttribute('aria-pressed',b.dataset.section===section));$('#heesu-btn').setAttribute('aria-pressed',section==='heesu');$('.heesu-count').textContent=section==='heesu'?'✓':FRIEND_RESTAURANTS.length+'곳 →';if($('#yoonhwan-btn')){$('#yoonhwan-btn').setAttribute('aria-pressed',section==='yoonhwan');$('#yoonhwan-count').textContent=section==='yoonhwan'?'✓':'5곳 →';}$('#search-area').hidden=section==='schedule';$('#filters').innerHTML=(foodSection()?['전체','추천만',...REGIONS]:['전체',...(C.exploreFilters||[]),...REGIONS,'먹거리','필수',...(C.city?[]:['아이 동반'])]).map(f=>`<button data-filter="${f}" aria-pressed="${filter===f}">${f}</button>`).join('');
$('#list-heading').innerHTML=section==='schedule'?`<span>DAY ${current+1} · ${esc(d.title)} · ${d.stops.filter(s=>s.visited).length}/${d.stops.length} 방문</span><button id="day-edit">숙소·날짜 설정</button>`:`<span>${foodSection()?friendName()+'의 맛집 리스트':'여행 후보지'} ${list.length}곳</span><span>${foodSection()?'핀을 눌러 메뉴와 주소 보기':'현재 날짜에 담아보세요'}</span>`;
let html='';if(section==='schedule'){html=`<div class="hotel-card"><span>⌂</span><div><small>오늘의 출발 · 돌아올 곳</small><strong>${esc(d.hotel?.name||'숙소를 설정해 주세요')}</strong></div><button id="hotel-edit">변경</button></div>`;list.forEach((p,i)=>{const stop=d.stops[i],prev=i?list[i-1]:d.hotel;if(prev)html+=transfer(prev,p,stop);html+=card(p,stop,i);});if(list.length&&d.hotel)html+=`<div class="transfer">⌂ 숙소로 돌아가기 ${external(directions(list[list.length-1],d.hotel),'길찾기')}</div>`;}else html=list.map(p=>card(p)).join('');
if(!list.length)html+=`<div class="empty"><span class="empty-icon">${foodSection()?FOOD_ICON:'⌁'}</span><h3>${section==='schedule'?'비워둔 하루, 어디로 갈까요?':foodSection()&&!FRIEND_RESTAURANTS.length?FRIEND+'의 맛집을 기다리고 있어요':'찾는 장소가 없어요'}</h3><p>${section==='schedule'?'장소 찾기에서 가고 싶은 곳을 담아보세요.':foodSection()&&!FRIEND_RESTAURANTS.length?'목록이 추가되면 상호명과 주요 메뉴를<br>지도에서 함께 볼 수 있어요.':'다른 검색어나 필터를 선택해 보세요.'}</p>${section==='schedule'?'<button id="go-explore">장소 찾아보기 →</button>':''}</div>`;
$('#place-list').innerHTML=html;$('#place-list').querySelectorAll('img').forEach(img=>img.onerror=()=>{const el=document.createElement('div');el.className='spot-thumb spot-placeholder';el.textContent='旅';img.replaceWith(el);});$('#undo-btn').disabled=!undo.length;
$('#map-title').textContent=foodSection()?friendName()+'의 맛집 지도':section==='explore'?C.exploreTitle||'홍콩과 마카오, 가고 싶은 곳':`Day ${current+1} · ${d.title}`;$('#map-subtitle').textContent=foodSection()?`${list.filter(located).length}곳 위치 표시${list.some(p=>!located(p))?' · '+list.filter(p=>!located(p)).length+'곳 지점 확인 중':''} · ${MAP_LABEL} 연결`:section==='explore'?`${list.length}곳의 여행 후보지`:`${d.stops.length}곳 · 나만의 방문 순서`;
$('#map-note').textContent=foodSection()?'핀을 누르면 메뉴·주소·'+MAP_LABEL+'. 가까운 이름은 확대하면 더 잘 보여요.':'점선은 방문 순서예요. 실제 이동 경로는 길찾기에서 확인하세요.';drawMap(fit);}
function changeSection(next){section=next;filter='전체';query='';$('#search').value='';render(true);}
function add(id){if(!available(getPlace(id)))return toast('지점과 영업 여부를 먼저 확인해 주세요.');mutate(()=>Planner.move(trip(),id,current));toast(`Day ${current+1}에 담았어요.`);}
function openDialog(title,content){$('#dialog-title').textContent=title;$('#dialog-body').replaceChildren();if(typeof content==='string')$('#dialog-body').innerHTML=content;else $('#dialog-body').append(content);if(!$('#editor').open)$('#editor').showModal();}
const close=()=>$('#editor').close();
function form(title,html,onSubmit){openDialog(title,`<form id="edit-form"><div class="form-grid">${html}</div><div class="form-actions"><button type="button" id="cancel-form">취소</button><button type="submit" class="primary">저장</button></div></form>`);$('#cancel-form').onclick=close;$('#edit-form').onsubmit=e=>{e.preventDefault();try{onSubmit(Object.fromEntries(new FormData(e.target)));close();}catch(error){toast(error.message);}};}
function editStop(id){const s=trip().days[current].stops.find(s=>s.id===id);form('시간과 메모',`<label>방문 시간<input name="time" type="time" value="${esc(s.time)}"></label><label>머무는 시간 (분)<input name="duration" type="number" min="0" max="1440" value="${s.duration}"></label><label class="wide">나의 메모<textarea name="note" maxlength="2000" placeholder="예약 번호, 주문할 메뉴, 준비물…">${esc(s.note)}</textarea></label>`,v=>mutate(()=>Object.assign(s,{time:v.time,duration:Number(v.duration),note:v.note})));}
function moveDialog(id){const assigned=trip().days.findIndex(d=>d.stops.some(s=>s.id===id));form('날짜 이동',`<label class="wide">이 장소를 언제 방문할까요?<select name="day"><option value="pool">일정에서 빼기 · 후보지에 보관</option>${trip().days.map((d,i)=>`<option value="${i}" ${assigned===i?'selected':''}>Day ${i+1} · ${esc(d.title)}</option>`).join('')}</select></label>`,v=>mutate(()=>Planner.move(trip(),id,v.day==='pool'?null:Number(v.day))));}
function settings(){const t=trip();form('여행 설정',`<label class="wide">여행 이름<input name="name" required maxlength="100" value="${esc(t.name)}"></label><label>출발 날짜<input type="date" name="start" value="${esc(t.start)}"></label><label>여행 일수<input type="number" name="count" min="1" max="30" required value="${t.days.length}"></label><p class="help wide">줄어드는 날짜에 담긴 장소는 후보지에서 다시 찾을 수 있어요. 시간·메모는 되돌리기로 복구할 수 있습니다.</p>`,v=>mutate(()=>{t.name=v.name.trim()||'나의 여행';t.start=v.start;const n=Number(v.count);while(t.days.length<n)t.days.push(Planner.day(t.days.length));t.days.length=n;}));}
function enteredPoint(v){let lat=Number(v.lat),lng=Number(v.lng);if(C.city==='shanghai'&&v.coordType==='gcj02'){[lng,lat]=coordtransform.gcj02towgs84(lng,lat);}return {lat,lng};}
const coordinateField=()=>C.city==='shanghai'?'<label class="wide">입력 좌표계<select name="coordType"><option value="wgs84">WGS84 · 일반 GPS / OpenStreetMap</option><option value="gcj02">GCJ-02 · 고덕지도 좌표</option></select></label>':'';
function hotelSettings(){const d=trip().days[current],h=d.hotel;form(`Day ${current+1} 숙소`, `<label class="wide">하루 제목<input name="title" maxlength="50" required value="${esc(d.title)}"></label><label class="wide">숙소 이름<input name="name" maxlength="300" value="${esc(h?.name||'')}" placeholder="예약한 숙소 이름"></label><label>위도<input type="number" step="any" min="-90" max="90" name="lat" value="${h?.lat??''}"></label><label>경도<input type="number" step="any" min="-180" max="180" name="lng" value="${h?.lng??''}"></label>${coordinateField()}<p class="help wide">${C.coordinateHelp||'구글지도에서 위치를 길게 누르거나 우클릭하면 좌표를 확인할 수 있어요.'} 이름을 비우면 숙소를 지웁니다.</p>`,v=>{if(v.name&&(!v.lat||!v.lng))throw Error('숙소의 위도와 경도를 함께 입력해 주세요.');mutate(()=>{d.title=v.title;d.hotel=v.name?{name:v.name,...enteredPoint(v)}:null;});drawMap(true);});}
function addCustom(){form('나만의 장소 추가',`<label class="wide">장소 이름<input name="name" required maxlength="300"></label><label class="wide">주소<input name="address" maxlength="500" placeholder="${MAP_LABEL}에 나온 주소"></label><label>위도<input name="lat" type="number" step="any" min="-90" max="90" required placeholder="${C.center?.[0]||22.28}…"></label><label>경도<input name="lng" type="number" step="any" min="-180" max="180" required placeholder="${C.center?.[1]||114.15}…"></label><label>지역<select name="region">${REGIONS.map(x=>`<option>${x}</option>`).join('')}</select></label><label>주요 메뉴<input name="menus" maxlength="300" placeholder="쉼표로 구분"></label><label class="wide">메모<textarea name="desc" maxlength="2000"></textarea></label>${coordinateField()}<p class="help wide">${C.coordinateHelp||'구글지도에서 위치를 길게 누르거나 우클릭해 좌표를 복사하세요.'} 추가한 장소는 현재 날짜에 담깁니다.</p>`,v=>{const p=Planner.place({...v,id:'custom-'+Planner.id(),...enteredPoint(v),menus:v.menus.split(',').map(s=>s.trim()).filter(Boolean)});if(!p)throw Error('장소 이름과 좌표를 확인해 주세요.');mutate(()=>{trip().custom.push(p);Planner.move(trip(),p.id,current);});toast('새 장소를 일정에 담았어요.');});}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportText(){const t=trip();const lines=[t.name,t.start||'날짜 미정',''];t.days.forEach((d,i)=>{lines.push(`Day ${i+1} ${Planner.date(t.start,i)} · ${d.title}`,`숙소: ${d.hotel?.name||'미정'}`);d.stops.forEach((s,j)=>{const p=getPlace(s.id);lines.push(`${j+1}. ${s.time||'시간 미정'} ${p.name}${s.visited?' [방문 완료]':''}`,p.address||'',p.menus?.length?'메뉴: '+p.menus.join(', '):'',s.note||'',google(p));});lines.push('');});download((C.cityLabel||'홍콩')+'-여행일정.txt',lines.join('\n'),'text/plain;charset=utf-8');}
function backup(){openDialog('여행 보관함',`<p class="help">일정은 이 브라우저에 저장돼요. 휴대폰으로 옮길 때는 공유 링크나 백업 파일을 사용하세요.</p><div class="backup-actions"><button id="backup-download">모든 여행 백업 다운로드 (.json)</button><button id="text-download">현재 여행을 텍스트로 저장</button><label>백업 파일 가져오기<input type="file" id="import-file" accept=".json,application/json"></label><button id="mobile-settings">여행 이름·날짜·일수 설정</button><button id="duplicate-trip">현재 여행 복제</button></div>`);$('#backup-download').onclick=()=>download((C.cityLabel||'홍콩')+'-여행-백업.json',JSON.stringify(db,null,2),'application/json');$('#text-download').onclick=exportText;$('#mobile-settings').onclick=settings;$('#duplicate-trip').onclick=()=>{const t=structuredClone(trip());t.id=Planner.id();t.name+=' · 복사';db.trips.push(t);db.active=t.id;undo=[];save();render(true);close();};$('#import-file').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>5000000)throw Error('5MB 이하의 백업을 선택해 주세요.');const raw=JSON.parse(await f.text());if(raw.version!==2||!Array.isArray(raw.trips)||!raw.trips.length||raw.trips.length>50)throw Error('올바른 여행 백업 파일이 아닙니다.');const imported=raw.trips.map(t=>{const x=Planner.normalize(t,catalog);x.id=Planner.id();return x;});db.trips.push(...imported);db.active=imported[0].id;undo=[];current=0;save();render(true);close();toast('기존 여행을 유지하고 백업을 추가했어요.');}catch(err){toast('가져오기 실패: '+err.message);}};}
async function share(){const url=location.href.split('#')[0]+'#'+Planner.hash(trip());try{await navigator.clipboard.writeText(url);toast('일정 공유 링크를 복사했어요.');}catch{openDialog('일정 공유 링크',`<p class="help">링크를 복사해 다른 기기에서 열어보세요.</p><textarea id="share-text" style="width:100%" readonly>${esc(url)}</textarea>`);$('#share-text').select();}if(location.protocol==='file:')toast('파일로 열었어요. 다른 기기에서는 사이트 주소로 접속하거나 백업 파일을 사용해 주세요.');}
$('#place-list').onclick=e=>{if(e.target.closest('#hotel-edit'))return hotelSettings();if(e.target.closest('#go-explore'))return changeSection('explore');const b=e.target.closest('[data-action]'),c=e.target.closest('.spot-card[data-id]');if(!c)return;if(!b){if(!e.target.closest('a,button,input,select,textarea'))focusPlace(c.dataset.id);return;}const id=c.dataset.id,act=b.dataset.action;if(act==='focus')focusPlace(id);if(act==='add')add(id);if(act==='edit')editStop(id);if(act==='move')moveDialog(id);if(act==='visited')mutate(()=>{const s=trip().days[current].stops.find(s=>s.id===id);s.visited=!s.visited;});if(act==='up'||act==='down')mutate(()=>{const stops=trip().days[current].stops,i=stops.findIndex(s=>s.id===id),j=i+(act==='up'?-1:1);if(j>=0&&j<stops.length)[stops[i],stops[j]]=[stops[j],stops[i]];});};
$('#place-list').onchange=e=>{if(e.target.dataset.mode){const id=e.target.dataset.mode,value=e.target.value;mutate(()=>{trip().days[current].stops.find(s=>s.id===id).mode=value;});}};
$('#place-list').ondragstart=e=>{const card=e.target.closest('[draggable]');if(!card)return;if(e.target.closest('button,a,select,input')){e.preventDefault();return;}e.dataTransfer.setData('text/plain',card.dataset.id);card.classList.add('dragging');};
$('#place-list').ondragover=e=>{if(section!=='schedule')return;e.preventDefault();document.querySelectorAll('.drop-before').forEach(c=>c.classList.remove('drop-before'));e.target.closest('[data-id]')?.classList.add('drop-before');};
$('#place-list').ondragend=()=>document.querySelectorAll('.dragging,.drop-before').forEach(c=>c.classList.remove('dragging','drop-before'));
$('#place-list').ondrop=e=>{if(section!=='schedule')return;e.preventDefault();const id=e.dataTransfer.getData('text/plain'),before=e.target.closest('[data-id]')?.dataset.id||null;if(id!==before&&getPlace(id))mutate(()=>Planner.move(trip(),id,current,before));};
$('#day-tabs').onclick=e=>{const b=e.target.closest('[data-day]');if(!b)return;current=Number(b.dataset.day);render(true);};$('#list-heading').onclick=e=>{if(e.target.closest('#day-edit'))hotelSettings();};
document.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>changeSection(b.dataset.section));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>setView(b.dataset.view,b.dataset.view==='map'));$('#heesu-btn').onclick=()=>{changeSection(section==='heesu'?'schedule':'heesu');if(section==='heesu')setView('map',true);};$('#filters').onclick=e=>{const b=e.target.closest('[data-filter]');if(b){filter=b.dataset.filter;render(true);}};$('#search').oninput=e=>{query=e.target.value;render(true);};$('#trip-select').onchange=e=>{db.active=e.target.value;current=0;undo=[];save();render(true);};$('#new-trip').onclick=()=>{const t=Planner.fresh();t.name='새 '+(C.tripName||'홍콩·마카오 여행');db.trips.push(t);db.active=t.id;current=0;undo=[];save();render(true);settings();};$('#settings-btn').onclick=settings;$('#share-btn').onclick=share;$('#backup-btn').onclick=backup;$('#add-btn').onclick=addCustom;$('#undo-btn').onclick=()=>{if(!undo.length)return;const restored=JSON.parse(undo.pop());db.trips[db.trips.findIndex(t=>t.id===db.active)]=restored;save();render();toast('이전 상태로 되돌렸어요.');};$('#close-dialog').onclick=close;$('#editor').onclick=e=>{if(e.target===$('#editor')){const r=e.target.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close();}};$('#fit-btn').onclick=()=>drawMap(true);$('#transit-btn').onclick=()=>{if(!map)return toast('지도를 먼저 불러와 주세요.');transit=!transit;if(transit)transitLayer.addTo(map);else map.removeLayer(transitLayer);$('#transit-btn').textContent=transit?'🚇 노선 숨기기':'🚇 노선 보기';$('#transit-btn').setAttribute('aria-pressed',transit);};$('#location-btn').onclick=()=>{if(!map||!navigator.geolocation)return toast('현재 위치를 사용할 수 없어요.');navigator.geolocation.getCurrentPosition(pos=>{locationLayer.clearLayers();const point=[pos.coords.latitude,pos.coords.longitude];L.circleMarker(point,{color:'#fff',fillColor:'#3185e9',fillOpacity:1,radius:8,weight:3}).addTo(locationLayer).bindTooltip('내 위치');map.setView(point,15);},()=>toast('위치 권한이나 연결 상태를 확인해 주세요.'),{enableHighAccuracy:true,timeout:10000});};$('.brand').onclick=e=>{e.preventDefault();changeSection('schedule');setView('plan');};window.addEventListener('hashchange',()=>{importHash();current=0;undo=[];save();render(true);});initState();initMap();render(true);

function layoutFoodLabels(){
 if(!map||!foodSection())return;
 const used=[],size=map.getSize();
 markers.forEach(marker=>{
  const tip=marker.getTooltip(),el=tip?.getElement();if(!el)return;
  const point=map.latLngToContainerPoint(marker.getLatLng());
  const width=el.offsetWidth,height=el.offsetHeight;
  if(point.x<0||point.y<0||point.x>size.x||point.y>size.y){el.style.visibility='hidden';return;}
  const positions=[[0,-20],[-width/2-22,-10],[width/2+22,-10],[0,height+27],[-width/2-22,-height-18],[width/2+22,-height-18]];
  let chosen=null;
  for(const [dx,dy] of positions){
   const box={x:point.x+dx-width/2,y:point.y+dy-height,w:width,h:height};
   if(box.x<8||box.y<85||box.x+width>size.x-8||box.y+height>size.y-45)continue;
   if(!used.some(b=>box.x<b.x+b.w+5&&box.x+box.w+5>b.x&&box.y<b.y+b.h+5&&box.y+box.h+5>b.y)){chosen={box,dx,dy};break;}
  }
  el.style.visibility=chosen?'visible':'hidden';
  if(chosen){used.push(chosen.box);tip.options.offset=L.point(chosen.dx,chosen.dy);tip.setLatLng(marker.getLatLng());}
 });
}

$('#place-list').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('.spot-card[data-id]')){e.preventDefault();focusPlace(e.target.dataset.id);}});

if($('#yoonhwan-btn'))$('#yoonhwan-btn').onclick=()=>{changeSection(section==='yoonhwan'?'schedule':'yoonhwan');if(section==='yoonhwan')setView('map',true);};
